[features]
seeds = false
skip-lint = false
[programs.devnet]
odf_dao = "7mcAL1zv1P5sdv6QE98NMvx1z9BPaLmQYzg3oRyJtpYB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ethan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "cp target/idl/*.json app/src/types"