[features]
seeds = false
skip-lint = false
[programs.localnet]
odf_dao = "FWhQz5nK4MaSu3haRq2g1MrSrHm84VxYHfQ7WorJ7Tev"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/MyDev/MyCode/OutDefine/create-defn-token/guideSecret.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "cp target/idl/*.json app/src/types"